CREATE SCHEMA `DATING`;
CREATE USER 'webuser'@'172.17.0.1' IDENTIFIED BY 'panaram1ks';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW, CREATE, ALTER, REFERENCES, INDEX, CREATE VIEW, CREATE ROUTINE,
ALTER ROUTINE, EVENT, DROP, TRIGGER ON `DATING`.* TO 'webuser'@'172.17.0.1';
FLUSH PRIVILEGES;



select * from DATABASECHANGELOG order by dateexecuted asc
